### ISSUE TITLE
Please define a style guide for this repo

### ISSUE THREAD

**Issue by mbrukman** [epw/find-libraries-for-books#4]
I'm a bit confused as to the preferred style guide in this repo, e.g.,

* `library.py` has 2-space indent
* `www/*.js` appear to have 4-space indent but also have tabs
* `www/*.html` also have tabs

I'm fine with 2-space indent everywhere, though traditional Python style guide is 4-space indent, but to each their own.

Once that's defined, we can fix existing files (presumably, we don't want a mix of spaces + tabs) and encode them into an [EditorConfig](https://editorconfig.org/) file to make it automatic for everyone.

**Comment by epw** [comment]
Yeah, this is what comes of writing the files across three computers each with their own unique Emacs configurations.

Until now I haven't really worked with other programmers outside of a company setting, so haven't worried about it too much, and I've never heard of EditorConfig. I'm slightly wary of adding a second configuration language to my Emacs, but that's probably not too costly overall.

I think I'd say 2-space indent everywhere, I tend to find 4-space uses up too much horizontal space. I'll figure out what I need to change so that emacs stops adding tabs into HTML and JavaScript files.
